# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

def sumFibEvens(maxnum):

    fibonacci = [1, 2]

    while fibonacci[-2] + fibonacci[-1] < maxnum:
        fibonacci.append(fibonacci[-2] + fibonacci[-1])

    print(sum([x for x in fibonacci if x % 2 == 0]))

maxnum = 4000000
sumFibEvens(maxnum)
